"""Hive job: read encrypted Parquet, decrypt via the crypto service, apply
Ranger masking, write the Hive table.

THE ORDER MATTERS AND IS DELIBERATE: decrypt, then mask, then write. The Hive
table stores the MASKED value, never the plaintext -- so even a direct file
read of the warehouse yields nothing sensitive. The plaintext exists only in
this process's memory, between the decrypt response and the mask call.

Masking rules come from Ranger policy. This module chooses nothing.
"""
from __future__ import annotations

import logging
import os
from datetime import date
from pathlib import Path

from pipeline.mask.ranger import apply_mask, get_provider

log = logging.getLogger(__name__)

DATABASE = "trips_warehouse"
TABLE = "trips"

# Encrypted column -> the masked output column it becomes.
COLUMN_MAP = {
    "bike_id": "bike_id_masked",
    "subscriber_type": "subscriber_type_masked",
    "start_station_name": "start_station_masked",
    "end_station_name": "end_station_masked",
    "start_station_id": "start_station_id_masked",
    "end_station_id": "end_station_id_masked",
}

# The audience the warehouse serves. Analysts see masked values; the
# data_steward view is a separate, access-controlled path and is NOT what the
# pipeline writes.
MASK_GROUP = os.environ.get("MASK_AUDIENCE_GROUP", "analyst")


def assert_no_plaintext_survives(masked_rows: list[dict],
                                 plaintext: dict[str, list]) -> None:
    """The masked output must not equal the plaintext for any masked column.

    A mask that returns its input unchanged -- a misconfigured MASK_NONE, an
    unhandled type -- is the failure this catches. Without it, a policy typo
    silently publishes PII.
    """
    leaked = []
    for col, out_col in COLUMN_MAP.items():
        src = plaintext.get(col, [])
        for i, row in enumerate(masked_rows):
            if i >= len(src):
                break
            original, out = src[i], row.get(out_col)
            if original in (None, "") or out is None:
                continue
            if str(out) == str(original):
                leaked.append(f"{out_col} equals its plaintext ({original!r})")
    if leaked:
        raise RuntimeError(
            "REFUSING TO WRITE: masking did not change these values:\n  "
            + "\n  ".join(sorted(set(leaked))[:10]))


def run(logical_date: date, parquet_path: Path, out_dir: Path, crypto) -> dict:
    import pyarrow.parquet as pq

    table = pq.read_table(parquet_path)
    rows = table.to_pylist()
    if not rows:
        raise RuntimeError(f"{parquet_path} has no rows")

    provider = get_provider()
    masks = provider.masks_for(DATABASE, TABLE, MASK_GROUP)
    log.info("masking via %s: %s", provider.name, masks)

    missing = set(COLUMN_MAP) - set(masks)
    if missing:
        raise RuntimeError(
            f"no Ranger masking policy for {sorted(missing)}. Refusing to write "
            f"an unmasked sensitive column -- add a policy to "
            f"config/ranger/hive_masking_policies.json.")

    plaintext: dict[str, list] = {}
    for col in COLUMN_MAP:
        cts = [r.get(f"{col}_encrypted") for r in rows]
        plaintext[col] = crypto.decrypt_column(col, cts)
        log.info("decrypted %d values for %s", len(plaintext[col]), col)

    out_rows = []
    for i, r in enumerate(rows):
        row = {
            "trip_id": r["trip_id"],
            "logical_date": r["logical_date"],
            "start_time": r["start_time"],
            "duration_minutes": r["duration_minutes"],
            "bikeid_blind_index": r.get("bike_id_blind_index"),
            "start_station_blind_index": r.get("start_station_name_blind_index"),
            "masked_by": provider.name,
        }
        for col, out_col in COLUMN_MAP.items():
            row[out_col] = apply_mask(masks[col], plaintext[col][i])
        out_rows.append(row)

    assert_no_plaintext_survives(out_rows, plaintext)

    out_dir.mkdir(parents=True, exist_ok=True)
    part = out_dir / f"dt={logical_date.isoformat()}"
    part.mkdir(parents=True, exist_ok=True)
    dest = part / "trips_masked.parquet"

    import pyarrow as pa
    pq.write_table(pa.Table.from_pylist(out_rows), dest)

    _write_hive_ddl(out_dir.parent / "trips_table.hql", out_dir)

    log.info("wrote %d masked rows to %s", len(out_rows), dest)
    return {"rows": len(out_rows), "hive_path": str(dest),
            "masked_by": provider.name, "masks_applied": masks}


def _write_hive_ddl(path: Path, warehouse_dir: Path) -> None:
    """External table over the masked Parquet, partitioned by date."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f"""-- Generated by pipeline/transform/hive_mask.py
CREATE DATABASE IF NOT EXISTS {DATABASE};

CREATE EXTERNAL TABLE IF NOT EXISTS {DATABASE}.{TABLE} (
    trip_id                   STRING,
    bikeid_masked             STRING,
    subscriber_type_masked    STRING,
    start_station_masked      STRING,
    end_station_masked        STRING,
    start_station_id_masked   STRING,
    end_station_id_masked     STRING,
    bikeid_blind_index        STRING,
    start_station_blind_index STRING,
    start_time                STRING,
    duration_minutes          INT,
    masked_by                 STRING
)
PARTITIONED BY (dt STRING)
STORED AS PARQUET
LOCATION '{warehouse_dir.resolve()}';

MSCK REPAIR TABLE {DATABASE}.{TABLE};
""")
