"""Resolve Secret Manager references in .env.local into a runtime env file.

WHY THIS EXISTS: a .env file holding literal secret values drifts silently.
Someone rotates a secret in GCP, the file keeps the old value, and the failure
surfaces later as a confusing auth error. Declaring the SM resource NAME and
resolving it at sync time makes drift structurally impossible -- the value is
never stored long-term, so it cannot be stale.

Usage:
    python scripts/secrets_sync.py            # resolve -> .env.local.resolved
    python scripts/secrets_sync.py --verify   # check names exist, no writes
    python scripts/secrets_sync.py --check-drift   # literal vs SM comparison
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / ".env.local"
TARGET = ROOT / ".env.local.resolved"

# SM_FOO=<resource name>  pairs with  FOO_VALUE=<literal override>
PREFIX = "SM_"
SUFFIX = "_VALUE"


def parse_env(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    if not path.exists():
        return out
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        out[k.strip()] = v.strip()
    return out


def _client():
    try:
        from google.cloud import secretmanager
    except ImportError:
        sys.exit("google-cloud-secret-manager is not installed.\n"
                 "  pip install google-cloud-secret-manager")
    return secretmanager.SecretManagerServiceClient()


def resolve_one(client, name: str) -> str:
    resp = client.access_secret_version(request={"name": name})
    return resp.payload.data.decode("utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--verify", action="store_true",
                    help="check every declared secret exists; write nothing")
    ap.add_argument("--check-drift", action="store_true",
                    help="compare literal *_VALUE entries against Secret Manager")
    args = ap.parse_args()

    if not SOURCE.exists():
        sys.exit(f"{SOURCE.name} not found. Copy .env.local.example to .env.local first.")

    env = parse_env(SOURCE)
    declared = {k[len(PREFIX):]: v for k, v in env.items()
                if k.startswith(PREFIX) and v}
    if not declared:
        sys.exit("no SM_* references declared in .env.local")

    literals = {k[:-len(SUFFIX)]: v for k, v in env.items()
                if k.endswith(SUFFIX) and v}

    # Literal mode needs no GCP call at all -- report and stop.
    if literals and not (args.verify or args.check_drift):
        missing = set(declared) - set(literals)
        if not missing:
            print("LITERAL MODE: every secret has a local value; no GCP call made.")
            print("  WARNING: literal values go stale silently when rotated in GCP.")
            print("  Run with --check-drift to compare against Secret Manager.")
            _write(env, literals)
            return 0

    client = _client()
    resolved: dict[str, str] = {}
    problems: list[str] = []
    drift: list[str] = []

    for key, name in sorted(declared.items()):
        try:
            value = resolve_one(client, name)
        except Exception as e:                     # noqa: BLE001 — reported, not swallowed
            problems.append(f"  {key}: {type(e).__name__}: {str(e).splitlines()[0]}")
            continue
        resolved[key] = value
        if key in literals and literals[key] != value:
            drift.append(key)
        print(f"  ok  {key:26s} <- {name.split('/secrets/')[-1]}")

    if problems:
        print("\nFAILED to resolve:", file=sys.stderr)
        print("\n".join(problems), file=sys.stderr)

    if args.check_drift:
        if drift:
            print(f"\nDRIFT: {len(drift)} literal value(s) differ from Secret Manager:")
            for k in drift:
                print(f"  {k}  (local .env.local is STALE — rotated in GCP?)")
            return 1
        print("\nno drift: local literals match Secret Manager")
        return 0

    if args.verify:
        print(f"\nverified {len(resolved)}/{len(declared)} secrets exist")
        return 1 if problems else 0

    if problems:
        return 1

    _write(env, resolved)
    return 0


def _write(env: dict[str, str], values: dict[str, str]) -> None:
    """Write the runtime env file, 0600."""
    lines = [
        "# GENERATED by scripts/secrets_sync.py — DO NOT EDIT, DO NOT COMMIT.",
        "# Regenerate with `make secrets-sync`. Gitignored.",
        "",
    ]
    for k, v in sorted(env.items()):
        if k.startswith(PREFIX) or k.endswith(SUFFIX):
            continue
        lines.append(f"{k}={v}")
    lines.append("")
    for k, v in sorted(values.items()):
        lines.append(f"{k}={v}")
    TARGET.write_text("\n".join(lines) + "\n")
    TARGET.chmod(0o600)
    print(f"\nwrote {TARGET.name} ({len(values)} secrets, mode 600)")


if __name__ == "__main__":
    sys.exit(main())
